package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;

   public Driver()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Driver(java.lang.String name)
   {
      this.name = name;
   }

}
