package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Rejection implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REJECTION_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "REJECTION_ID_SEQ", name = "REJECTION_ID_GENERATOR")
    private java.lang.Long id;

    public Rejection() {
    }
    
    public Rejection(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}